@startuml

package "App" {

  package "FrontEnd" {
    [view]
  }

  package "BackEnd" {
    package "ViewObject" {
        view --> [controller]
        controller --> [decorator]
      }

      package "BusinessLogic" {
        controller --> [service]
        service --> [repository]
        service --> [factory]
      }

      package "DataAccessObject" {
        [model] <|.. [searchable]
        model <|.. [finder]
        controller --> model
        factory --> model
        repository --> model
      }
  }

  package "DataTransferObject" {
    BackEnd --> [form]
  }

  package "Util" {
    view --> [helper]
  }
}

package "Asset" {
  view -> Style
  view -> Script

  package "Style" {
    [layout] <|.. [module]
    layout <|.. [base]
    module <|.. base
  }

  package "Script" {
    [main] <|.. [util]
  }
}

package "DataStore" {
  model --> [mariadb]
  model --> [elasticsearch]
  [redis]
}

@enduml
