/'
## Setup
1. Install graphviz into MacOSX
$ brew install graphviz

2. Install PlantUML integration for IntelliJ
Preferences -> Plugins -> "PlantUML integration"
'/
@startuml

title My 100 Tales Components by @yuzutas0

package "Client" {
  [browser]
}

cloud Public {
  browser -- Public
}

node "CentOS (production) / MacOSX (development)" {
  Public -- [nginx]
  nginx -- [unicorn]

  package "View" {
    [view] -> unicorn

    package "Style" {
      view -> Style
      [layout] <|.. [module]
      layout <|.. [base]
      module <|.. base
    }

    package "Script" {
      view -> Script
      [main] <|.. [util]
      [main] <|.. [template]
    }
  }

  package "Controller" {
    unicorn --> [controller]
    controller --> view
    controller <|.. [handler]

    package "ViewObject" {
      view --> [helper]
      controller --> [decorator]
    }
  }

  package "Model" {

    package "DTO" {
      [form]
    }

    package "BusinessLogic" {
      controller --> [service]
      service --> [repository]
      service --> [factory]
    }

    package "DAO" {
      [model]
      model <|.. [searchable]
      model <|.. [finder]
      factory --> model
      repository --> model
    }
  }

  node "Docker (only development environment)" {

    database "Database" {
      model --> [mariadb]
    }

    database "KVS" {
      model --> [redis]
    }

    database "SearchEngine" {
      model --> [elasticsearch]
    }
  }
}

@enduml
